spring.application.name=BankingManagementSystem

    spring.datasource.url=jdbc:postgresql://localhost:5432/bankingmanagementsystem
spring.datasource.username=postgres
spring.datasource.password=helloworld
spring.datasource.driver-class-name=org.postgresql.Driver

# Optional Hibernate configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Custom Server Port
server.port=8080